### ISSUE TITLE
Vector errors after extensive split/contatenations

### ISSUE THREAD

**Issue by bbangert** [sabiwara/aja#6]
Splitting and concatenating vectors eventually results in an error.

Minimal reproduction case:

```elixir
  def splits(amount) do
    Enum.reduce(0..amount, vec([]), fn i, acc ->
      index = Enum.random(0..vec_size(acc))
      {left, right} = Vector.split(acc, index)
      Vector.append(left, i) +++ right
    end)
  end
```

Passing in `10000` on my system is sufficient to cause this error:
```
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, nil)
    (aja 0.7.0) lib/vector/builder.ex:135: Aja.Vector.Builder.do_from_trie/4
    (aja 0.7.0) lib/vector/raw.ex:225: Aja.Vector.Raw.concat_vector/2
    (aja 0.7.0) lib/vector.ex:468: Aja.Vector.concat/2
    (elixir 1.17.2) lib/enum.ex:4415: Enum.reduce_range/5
    iex:3: (file)
```

Changing the arguments to as low as `8500` worked once, but then threw the error afterwards.

**Comment by bbangert** [comment]
To make this fail more consistently (removing the random bit), here's an updated version where I tracked down the one that breaks it:
```elixir
  def splits(amount) do
    Enum.reduce(0..amount, vec([1, 2, 3]), fn i, acc ->
      index = div(vec_size(acc), 2)
      {left, right} = Vector.split(acc, index)
      Vector.concat(Vector.append(left, i), right)
    end)
  end
```

Using `16381` throws the error, any number under that is fine.

**Comment by sabiwara** [comment]
Thank you @bbangert for the report and the precise reproduction 💜

**Comment by bbangert** [comment]
Hi @sabiwara! Just wanted to elaborate that the project I was working on that used Aja, actually is better suited using a different data structure ([gb_sets + Map for a sorted unique key-set with consistent key access](https://github.com/bbangert/sooth/commit/34fc5b2be0d6b46922d44a0268ee62158b1527c1)), so I'm not using Aja at the moment. So there's no urgency on a fix and I found Aja a lovely library thus far. 

I only ran into this particular situation because I was doing frequent sorted insertions into an Aja.Vector. I'm a bit new to Elixir/Erlang and hadn't done more research into existing data structures that might be better suited for this use-case.

Thanks!
